apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: twitter-clone
spec:
  project: default
  source:
    path: helm-chart
    repoURL: https://github.com/example/twitter-clone.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
